### ISSUE TITLE
FULL OUTER JOINS not supported in SQLite3

### ISSUE THREAD

**Issue by maxgrok** [learn-co-curriculum/sql-joins-readme#11]
The example at the end does not work with SQLite3.

**Comment by bryanhou1** [comment]
to add to what @maxgrok had said, It seems that RIGHT OUTER JOINS isn't supported either

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We're currently rewriting the curriculum and updating all of our materials. We'll prioritize correcting this information in upcoming releases of this curriculum.

Thanks for contributing! 💙
