### ISSUE TITLE
Boilerplate example appears to be incorrect

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/sql-joins-readme#17]
The boilerplate example for LEFT OUTER JOIN seems to be wrong when compared to the actual example that is given. It says "LEFT JOIN" instead of "LEFT OUTER JOIN" and there is no space around the "=".

----------text:

Let's take a look at a boiler-plate LEFT OUTER JOIN:

SELECT column_name(s)
FROM first_table
LEFT JOIN second_table
ON first_table.column_name=second_table.column_name;
Now let's try it out on our pets_database.

WRITING LEFT OUTER JOINS
Execute the following command in your sqlite3> prompt in your terminal:

SELECT Cats.name, Cats.breed, Owners.name 
FROM Cats 
LEFT OUTER JOIN Owners 
ON Cats.owner_id = Owners.id;

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
