### ISSUE TITLE
LEFT JOIN VS LEFT OUTER JOIN

### ISSUE THREAD

**Issue by azharshahstl** [learn-co-curriculum/sql-joins-readme#18]
Boiler plate for LEFT OUTER JOIN

SELECT column_name(s)
FROM first_table
LEFT JOIN second_table
ON first_table.column_name=second_table.column_name;

Example for LEFT OUTER JOIN

SELECT Cats.name, Cats.breed, Owners.name 
FROM Cats 
LEFT OUTER JOIN Owners 
ON Cats.owner_id = Owners.id;

Should the OUTER be included or not?

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
