### ISSUE TITLE
RIGHT JOIN AND FULL OUTER JOIN

### ISSUE THREAD

**Issue by thistonyb** [learn-co-curriculum/sql-joins-readme#19]
It might be good to note that SQLite does not support either RIGHT JOIN or FULL OUTER JOIN.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
