### ISSUE TITLE
needs review

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/sql-joins-readme#2]
accidentally merged my PR on this so just opening an issue instead. 

@AnnJohn @jmburges

**Comment by jmburges** [comment]
@SophieDeBenedetto make sure to assign me! I filter by open things so once it gets merged it's marked as closed and I'll miss it :(

**Comment by jmburges** [comment]
made some comments

**Comment by SophieDeBenedetto** [comment]
@jmburges i don't see your comments...

**Comment by jmburges** [comment]
closing. All good from PR #1
