### ISSUE TITLE
SQL Joins Readme

### ISSUE THREAD

**Issue by emilia-m26** [learn-co-curriculum/sql-joins-readme#20]
Hello,

The SQL Joins readme seems to be inaccurate.

I follow the code-along information and it populates the information on the snippets without the columns labeled, which doesn't really interrupt the lesson at all.  However, once you get to the statement "Let's run that query again, this time aliasing the name column of the Owners table as owners_name, using the AS keyword", you understand what the reason was for the labels to show previously.  When you use the AS keyword, the change will not show if the labels did not show before.

It's missing the steps of (.headers on) and (.mode column)

**Comment by sgharms** [comment]
Great usability insight. Rolling in right now.
