### ISSUE TITLE
RIGHT and FULL OUTER JOINs

### ISSUE THREAD

**Issue by just-Bri** [learn-co-curriculum/sql-joins-readme#6]
While working through a codealong I tried running a JOIN in sqlite3 and got this:
sqlite> SELECT Cats.name, Cats.breed, Owners.name
   ...> FROM Cats
   ...> RIGHT JOIN Owners
   ...> ON Cats.owner_id = Owners.id;
Error: RIGHT and FULL OUTER JOINs are not currently supported

Was I supposed to be using a newer/different version of SQL or SQLite?

**Comment by AnnJohn** [comment]
hi @ruchiramani can you take a look at this issue and run it on your end, and see if there's a larger issue to this.

@reifnotreef sorry for the trouble you're having, but we're looking into it.

**Comment by just-Bri** [comment]
Sorry, you can drop this Issue.

I scrolled passed the readme that tells me it wont work with SqLite3!

**Comment by AnnJohn** [comment]
thanks!
